#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTTMUX,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Move_Library.c"
#include "rdpartyrobotcdr-3.0\drivers\hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.0\drivers\hitechnic-irseeker-v2.h"

const tMUXSensor LeftIR = msensor_S2_2;
const tMUXSensor RightIR = msensor_S2_3;

unsigned int StartWait = 0;


int DetectIRBeacon()
{
	int dirAC_1 = 0; // the translated directional value.
  int dirAC_2 = 0;
	int WhichPeg = 0;   // the value identifying which column the beacon is on

	//eraseDisplay();

	//read the current modulated signal direction
	dirAC_1 = HTIRS2readACDir(LeftIR);
	dirAC_2 = HTIRS2readACDir(RightIR);

	if(dirAC_1 <= 5)
	{
		if(dirAC_2 == 0)
			WhichPeg = 1;//1
		else
			WhichPeg = 1;//2
	}
	else if(dirAC_1 == 6)
		WhichPeg = 1;//2
	else if(dirAC_1 >= 7)
		WhichPeg = 1;//3
	else
		WhichPeg = 1;//0

	// display info
	nxtDisplayCenteredTextLine(2, "Pos=%d,D1=%d,D2=%d", WhichPeg,dirAC_1,dirAC_2);

	return WhichPeg;
}

void initializeRobot()
{
		// Set DSP mode to 1200 Hz.
  tHTIRS2DSPMode _mode = DSP_1200;

	nMotorEncoder[LeftFront] = 0;
	nMotorEncoder[LeftBack] = 0;
	nMotorEncoder[RightFront] = 0;
	nMotorEncoder[RightBack] = 0;
	disableDiagnosticsDisplay();

	wait1Msec(500);

	while(nNxtButtonPressed != 3)
	{
		DetectIRBeacon();

		if(nNxtButtonPressed == 1)
			StartWait = StartWait + 1000;
		else if (nNxtButtonPressed == 2)
			if(StartWait > 0)
				StartWait = StartWait - 1000;
		else
		{
			//Do nothing
		}
		nxtDisplayCenteredTextLine(0, "%d", StartWait);
		wait1Msec(100);
	}

	bDisplayDiagnostics = true;
}

task LiftSlide ()
{
	RaiseSlideLift(90, 3500);
}
task RaiseArm ()
{
	RaiseArticArm(100, 3600);
}
task LowerArm ()
{
	RaiseArticArm(-75, 3600);
}

task main ()
{
	initializeRobot();
  waitForStart(); // Wait for the beginning of autonomous phase.
	wait1Msec(StartWait);

	int WhichPeg = 0;   // the value identifying which column the beacon is on

	eraseDisplay();

	WhichPeg = DetectIRBeacon();

	if(WhichPeg == 3)
	{
		StartTask(LiftSlide);
		Move(60, 60, 700, 700);
		Move(60, -60, SPIN(47), SPIN(47));
		Move(100, 100, 4250, 4250);
		Move(60, 60, 1500, 1500);
		RaiseSlideLift(-90, 3500);
		Move(-100, -100, 4500, 4500);
	}
	else if(WhichPeg == 2)
	{
		StartTask(LiftSlide);
		StartTask(RaiseArm);
		Move(100, 100, 3800, 3800);
		Move(60, -60, SPIN(43), SPIN(43));
		Move(100, 100, 1600, 1600);
		Move(60, 60, 1300, 1300);
		RaiseSlideLift(-100, 3500);
		StartTask(LowerArm);
		Move(-100, -100, 2500, 2500);
		Move(-60, 60, SPIN(49), SPIN(49));
		Move(-100, -100, 4000, 4000);
	}
	else if(WhichPeg == 1)
	{
		StartTask(LiftSlide);
		Move(100, 100, 6850, 6850);
		Move(60, -60, SPIN(39), SPIN(39));
		Move(60, 60, 2000, 2000);
		RaiseSlideLift(-90, 3500);
		Move(-100, -100, 2000, 2000);
		Move(-60, 60, SPIN(40), SPIN(40));
		Move(-100, -100, 6000, 6000);
	}
	while(1)
	{}
}
