#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.0\drivers\hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.0\drivers\hitechnic-eopd.h"

const tMUXSensor HTEOPD = msensor_S2_2;

task main()
{
	int kError = 0;
	int kScale = 1;
	int distance = 0;
	int rawEOPD = 0;
	int processedEOPD;

	HTEOPDsetLongRange(HTEOPD);

	while(1)
	{
		eraseDisplay();

		rawEOPD = HTEOPDreadRaw(HTEOPD);
		distance = ( (kScale / sqrt(rawEOPD)) - kError );
		processedEOPD = HTEOPDreadProcessed(HTEOPD);

		nxtDisplayTextLine(2, "Raw = %d", rawEOPD);
		nxtDisplayTextLine(4, "Processed = %d", processedEOPD);
		nxtDisplayTextLine(6, "Distance = %d", distance);
		wait1Msec(100);
	}
}
