#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTTMUX,         sensorAnalogInactive)
#pragma config(Motor,  motorA,          frontLamp,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          backLamp,      tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.0/drivers/hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.0/drivers/hitechnic-force.h"

// Give the sensor a nice easy to use name
const tMUXSensor F_Force = msensor_S2_4; //Setup for the front force sensor
const tMUXSensor B_Force = msensor_S2_1; //Setup for the back force sensor

int F_val = 0; //variables for the front sensor values
int B_val = 0; //variables for the back sensor value

void OnFrontLamp()
{
  motor[frontLamp] = 100;
}
void OffFrontLamp()
{
  motor[frontLamp] = 0;
}
void OnBackLamp()
{
  motor[backLamp] = 100;
}
void OffBackLamp()
{
  motor[backLamp] = 0;
}
task FrontDetectRing()
{
	while(1)
	{
		if(F_val > 250)
			OnFrontLamp();
		else
			OffFrontLamp();
		wait1Msec(50);
	}
}
task BackDetectRing()
{
	while(1)
	{
		if(B_val > 250)
			OnBackLamp();
		else
			OffBackLamp();
		wait1Msec(50);
	}
}

task main()
{
  eraseDisplay(); // Clear the nxt screen
  StartTask(FrontDetectRing);
  StartTask(BackDetectRing);

  while(1)
  {
    // Read the sensor value
    F_val = HTFreadSensor(F_Force); //Put the sensor values into the variables created
    B_val = HTFreadSensor(B_Force); //Put the sensor values into the variables created

    nxtDisplayTextLine(2, "Front: %d", F_val); //Display the sensor value for the front force sensor
    nxtDisplayTextLine(5, "Back: %d", B_val);  //Display the sensor value for the back force sensor

    if(F_val < 250)
    	nxtDisplayTextLine(3, "F_Ring: Normal");
    else
    	nxtDisplayTextLine(3, "F_Ring: Weighted");

    if(B_val < 250)
    	nxtDisplayTextLine(6, "B_Ring: Normal");
    else
    	nxtDisplayTextLine(6, "B_Ring: Weighted");

    wait1Msec(50); 														 //Wait to give time for the nxt screen to display the values before they refresh
	}
}
