#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,      tmotorTetrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void MotorLeftFront(int MtrPwr, int MtrDur)
{
 nMotorPIDSpeedCtrl[LeftFront] = mtrSpeedReg;
 nMotorEncoder[LeftFront] = 0;
 nMotorEncoderTarget[LeftFront] = MtrDur;
 motor[LeftFront] = MtrPwr;

 while (nMotorRunState[LeftFront] != runStateIdle)
 {
   //wait
 }

 motor[LeftFront] = 0;
 nMotorPIDSpeedCtrl[LeftFront] = mtrNoReg;
}

void MotorLeftBack(int MtrPwr, int MtrDur)
{
 nMotorPIDSpeedCtrl[LeftBack] = mtrSpeedReg;
 nMotorEncoder[LeftBack] = 0;
 nMotorEncoderTarget[LeftBack] = MtrDur;
 motor[LeftBack] = MtrPwr;

 while (nMotorRunState[LeftBack] != runStateIdle)
 {
   //wait
 }

 motor[LeftBack] = 0;
 nMotorPIDSpeedCtrl[LeftBack] = mtrNoReg;
}

void MotorRightBack(int MtrPwr, int MtrDur)
{
 nMotorPIDSpeedCtrl[RightBack] = mtrSpeedReg;
 nMotorEncoder[RightBack] = 0;
 nMotorEncoderTarget[RightBack] = MtrDur;
 motor[RightBack] = MtrPwr;

 while (nMotorRunState[RightBack] != runStateIdle)
 {
   //wait
 }

 motor[RightBack] = 0;
 nMotorPIDSpeedCtrl[RightBack] = mtrNoReg;
}

void MotorRightFront(int MtrPwr, int MtrDur)
{
 nMotorPIDSpeedCtrl[RightFront] = mtrSpeedReg;
 nMotorEncoder[RightFront] = 0;
 nMotorEncoderTarget[RightFront] = MtrDur;
 motor[RightFront] = MtrPwr;

 while (nMotorRunState[RightFront] != runStateIdle)
 {
   //wait
 }

 motor[RightFront] = 0;
 nMotorPIDSpeedCtrl[RightFront] = mtrNoReg;
}

void MotorArticArm(int MtrPwr, int MtrDur)
{
 nMotorPIDSpeedCtrl[ArticArm] = mtrSpeedReg;
 nMotorEncoder[ArticArm] = 0;
 nMotorEncoderTarget[ArticArm] = MtrDur;
 motor[ArticArm] = MtrPwr;

 while (nMotorRunState[ArticArm] != runStateIdle)
 {
   //wait
 }

 motor[ArticArm] = 0;
 nMotorPIDSpeedCtrl[ArticArm] = mtrNoReg;
}

void MotorSlideLift(int MtrPwr, int MtrDur)
{
 nMotorPIDSpeedCtrl[SlideLift] = mtrSpeedReg;
 nMotorEncoder[SlideLift] = 0;
 nMotorEncoderTarget[SlideLift] = MtrDur;
 motor[SlideLift] = MtrPwr;

 while (nMotorRunState[SlideLift] != runStateIdle)
 {
   //wait
 }

 motor[SlideLift] = 0;
 nMotorPIDSpeedCtrl[SlideLift] = mtrNoReg;
}

task main()
{
		MotorLeftFront(70, 500);
		MotorLeftFront(-70, 500);
		wait10Msec(100);

		MotorLeftBack(70, 1000);
		MotorLeftBack(-70, 1000);
		wait10Msec(100);

		MotorRightFront(70, 1000);
		MotorRightFront(-70, 1000);
		wait10Msec(100);

		MotorRightBack(70, 1000);
		MotorRightBack(-70, 1000);
		wait10Msec(100);

		MotorArticArm(70, 1000);
		MotorArticArm(-70, 1000);
		wait10Msec(100);

		MotorSlideLift(70, 1000);
		MotorSlideLift(-70, 1000);
		wait10Msec(100);
}
