#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTTMUX,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.0\drivers\hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.0\drivers\hitechnic-touchmux.h"

const tMUXSensor HTEOPD = msensor_S2_1;
const tMUXSensor IR_right = msensor_S2_3;
const tMUXSensor IR_left = msensor_S2_2;
const tMUXSensor F_Force = msensor_S2_4;
const tMUXSensor B_Force = msensor_S2_1;
const tMUXSensor SlideLift_Touch = msensor_S3_2;
const tMUXSensor ArticArm_Touch = msensor_S3_3;
