#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,            tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	//initializeRobot();
  waitForStart();   // wait for start of tele-op phase

	int MtrPwrLeftFront = 0;
	int MtrPwrLeftBack = 0;
	int MtrPwrRightFront = 0;
	int MtrPwrRightBack = 0;
	int MtrPwrSlideLift = 0;
	int MtrPwrArticArm = 0;

//bFloatDuringInactiveMotorPWM = false;
	nMotorPIDSpeedCtrl[SlideLift] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[ArticArm] = mtrSpeedReg;

	nMotorEncoder[SlideLift] = 0;
	nMotorEncoder[ArticArm] = 0;

	while(1)
	{
			alive();
			getJoystickSettings(joystick);

			//Handle SlideLift Power Settings
			if(joy2Btn(4) == 1)
					MtrPwrSlideLift = 100;
			else if(joy2Btn(2) == 1)
					MtrPwrSlideLift = -100;
			else
					MtrPwrSlideLift = 0;

			//Handle ArticArm Power Settings
			if(joy2Btn(3) == 1)
					MtrPwrArticArm = 100;
			else if(joy2Btn(1) == 1)
					MtrPwrArticArm = -60;
			else
					MtrPwrArticArm = 0;

			//Handle Drive Train Power Settings For the Two Joysticks
			float RtPwr = ((joystick.joy1_y1) * 0.78125);
			float LtPwr = ((joystick.joy1_y2) * 0.78125);

			//If the Value Given By the Joysticks is too low to Move the Drive Train, Set the Power to 0
			if(abs(RtPwr) <= 20)
					RtPwr = 0;
			if(abs(LtPwr) <= 20)
					LtPwr = 0;

			////////////////////////////////
			//Drive Train Power Overwrites//
			////////////////////////////////

			//If Button 4 is Pressed, Set New Power Values to Make the Robot Move Forward
			if(joy1Btn(4) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightFront = 100;
					MtrPwrRightBack = 100;
					MtrPwrLeftFront = 100;
					MtrPwrLeftBack = 100;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightFront = 60;
					MtrPwrRightBack = 60;
					MtrPwrLeftFront = 60;
					MtrPwrLeftBack = 60;
				}
				else
			  {
			  	MtrPwrRightFront = 40;
					MtrPwrRightBack = 40;
					MtrPwrLeftFront = 40;
					MtrPwrLeftBack = 40;
			  }
			}
			//If Button 2 is Pressed, Set New Power Values to Make the Robot Move Backward
			else if(joy1Btn(2) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightFront = -100;
					MtrPwrRightBack = -100;
					MtrPwrLeftFront = -100;
					MtrPwrLeftBack = -100;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightFront = -60;
					MtrPwrRightBack = -60;
					MtrPwrLeftFront = -60;
					MtrPwrLeftBack = -60;
				}
				else
			 	{
					MtrPwrRightFront = -40;
					MtrPwrRightBack = -40;
					MtrPwrLeftFront = -40;
					MtrPwrLeftBack = -40;
				}
			}
			//If Button 3 is Pressed, Set New Power Values to Make the Robot Spin Clockwise
			else if(joy1Btn(3) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightFront = -100;
					MtrPwrRightBack = -100;
					MtrPwrLeftFront = 100;
					MtrPwrLeftBack = 100;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightFront = -60;
					MtrPwrRightBack = -60;
					MtrPwrLeftFront = 60;
					MtrPwrLeftBack = 60;
				}
				else
				{
					MtrPwrRightFront = -40;
					MtrPwrRightBack = -40;
					MtrPwrLeftFront = 40;
					MtrPwrLeftBack = 40;
				}
			}
			//If Button 1 is Pressed, Set New Power Values to Make the Robot Spin Anticlockwise
			else if(joy1Btn(1) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightFront = 100;
					MtrPwrRightBack = 100;
					MtrPwrLeftFront = -100;
					MtrPwrLeftBack = -100;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightFront = 60;
					MtrPwrRightBack = 60;
					MtrPwrLeftFront = -60;
					MtrPwrLeftBack = -60;
				}
				else
				{
					MtrPwrRightFront = 40;
					MtrPwrRightBack = 40;
					MtrPwrLeftFront = -40;
					MtrPwrLeftBack = -40;
				}
			}

			//If Button 7 is Pressed, Turn 90 Degrees Left
			else if(joy1Btn(7) == 1)
			{
				motor[RightFront] = 60;
		 		motor[RightBack] = 60;
		 		motor[LeftFront] = -60;
		 		motor[LeftBack] = -60;
				wait10Msec(100);
			}
			//If Button 8 is Pressed, Turn 90 Degrees Right
			else if(joy1Btn(8) == 1)
			{
				motor[RightFront] = -60;
		 		motor[RightBack] = -60;
		 		motor[LeftFront] = 60;
		 		motor[LeftBack] = 60;
				wait10Msec(100);
			}
			//If No Buttons Are Pressed, Move The Robot According to the Joysticks
			else
		  {
				MtrPwrRightFront = LtPwr;
				MtrPwrRightBack = LtPwr;
				MtrPwrLeftFront = RtPwr;				MtrPwrLeftBack = RtPwr;
		  }

		  motor[RightFront] = MtrPwrRightFront;
		  motor[RightBack] = MtrPwrRightBack;
		  motor[LeftFront] = MtrPwrLeftFront;
		  motor[LeftBack] = MtrPwrLeftBack;
		  motor[SlideLift] = MtrPwrSlideLift;
		  motor[ArticArm] = MtrPwrArticArm;

		  if(joy1Btn(7) == 0 && joy1Btn(8) == 0)
				wait1Msec(20);
	}
}
