#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTTMUX,         sensorAnalogInactive)
#pragma config(Motor,  motorA,          frontLamp,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          backLamp,      tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Move_Library.c"
#include "rdpartyrobotcdr-3.0\drivers\hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.0\drivers\hitechnic-touchmux.h"
#include "rdpartyrobotcdr-3.0/drivers/hitechnic-force.h"
//#include "rdpartyrobotcdr-3.0\drivers\hitechnic-eopd.h"
//#include "rdpartyrobotcdr-3.0\drivers\hitechnic-irseeker-v2.h"


const tMUXSensor F_Force = msensor_S2_4;
const tMUXSensor B_Force = msensor_S2_1;
const tMUXSensor LeftIR = msensor_S2_2;
const tMUXSensor RightIR = msensor_S2_3;

int F_val = 0; //variables for the front sensor values
int B_val = 0; //variables for the back sensor value

void OnFrontLamp()
{
  motor[frontLamp] = 100;
}
void OffFrontLamp()
{
  motor[frontLamp] = 0;
}
void OnBackLamp()
{
  motor[backLamp] = 100;
}
void OffBackLamp()
{
  motor[backLamp] = 0;
}
task FrontDetectRing()
{
	while(1)
	{
		if(F_val > 250)
			OnFrontLamp();
		else
			OffFrontLamp();
		wait1Msec(50);
	}
}
task BackDetectRing()
{
	while(1)
	{
		if(B_val > 250)
			OnBackLamp();
		else
			OffBackLamp();
		wait1Msec(50);
	}
}

bool taskEntered = false;
bool taskEnteredArtArm = false;
bool taskEnteredSlideLift = false;

//returns true value if down button is pressed on Dpad on joystick 2, returns false value if down button on joystick 2 is not pressed.
 bool isUPJoy2DPadPressed(TJoystick js)
{
  if(js.joy2_TopHat == 0) return true;
  else return false;
}
//returns true value if down button is pressed on Dpad on joystick 2, returns false value if down button on joystick 2 is not pressed.
 bool isDOWNJoy2DPadPressed(TJoystick js)
{
  if(js.joy2_TopHat == 4) return true;
  else return false;
}
//returns true value if left button is pressed on Dpad on joystick 2, returns false value if left button on joystick 2 is not pressed.
 bool isLEFTJoy2DPadPressed(TJoystick js)
{
  if(js.joy2_TopHat == 6) return true;
  else return false;
}
//returns true value if right button is pressed on Dpad on joystick 2, returns false value if right button on joystick 2 is not pressed.
 bool isRIGHTJoy2DPadPressed(TJoystick js)
{
  if(js.joy2_TopHat == 2) return true;
  else return false;
}
//returns true value if upleft button is pressed on Dpad on joystick 2, returns false value if upleft button on joystick 2 is not pressed.
 bool isUPLEFTJoy2DPadPressed(TJoystick js)
{
  if(js.joy2_TopHat == 1) return true;
  else return false;
}
//returns true value if upright button is pressed on Dpad on joystick 2, returns false value if upright button on joystick 2 is not pressed.
 bool isUPRIGHTJoy2DPadPressed(TJoystick js)
{
  if(joystick.joy2_TopHat == 7) return true;
  else return false;
}
//returns true value if downleft button is pressed on Dpad on joystick 2, returns false value if downleft button on joystick 2 is not pressed.
 bool isDOWNLEFTJoy2DPadPressed(TJoystick js)
{
  if(js.joy2_TopHat == 5) return true;
  else return false;
}
//returns true value if downright button is pressed on Dpad on joystick 2, returns false value if downright button on joystick 2 is not pressed.
 bool isDOWNRIGHTJoy2DPadPressed(TJoystick js)
{
  if(js.joy2_TopHat == 3) return true;
  else return false;
}

///

//returns true value if up button is pressed on Dpad on joystick 1, returns false value if up button on joystick 2 is not pressed.
 bool IsUPJoy1DPadPressed(TJoystick js)
{
  if(js.joy1_TopHat == 0)
  	return true;
  else return false;
}
//returns true value if down button is pressed on Dpad on joystick 1, returns false value if down button on joystick 2 is not pressed.
 bool isDOWNJoy1DPadPressed(TJoystick js)
{
  if(js.joy1_TopHat == 4) return true;
  else return false;
}
//returns true value if left button is pressed on Dpad on joystick 2, returns false value if left button on joystick 2 is not pressed.
 bool isLEFTJoy1DPadPressed(TJoystick js)
{
  if(js.joy1_TopHat == 6) return true;
  else return false;
}
//returns true value if right button is pressed on Dpad on joystick 2, returns false value if right button on joystick 2 is not pressed.
 bool isRIGHTJoy1DPadPressed(TJoystick js)
{
  if(js.joy1_TopHat == 2) return true;
  else return false;
}
//returns true value if upleft button is pressed on Dpad on joystick 2, returns false value if upleft button on joystick 2 is not pressed.
 bool isUPLEFTJoy1DPadPressed(TJoystick js)
{
  if(js.joy1_TopHat == 1) return true;
  else return false;
}
//returns true value if upright button is pressed on Dpad on joystick 2, returns false value if upright button on joystick 2 is not pressed.
 bool isUPRIGHTJoy1DPadPressed(TJoystick js)
{
  if(joystick.joy1_TopHat == 7) return true;
  else return false;
}
//returns true value if downleft button is pressed on Dpad on joystick 2, returns false value if downleft button on joystick 2 is not pressed.
 bool isDOWNLEFTJoy1DPadPressed(TJoystick js)
{
  if(js.joy1_TopHat == 5) return true;
  else return false;
}
//returns true value if downright button is pressed on Dpad on joystick 2, returns false value if downright button on joystick 2 is not pressed.
 bool isDOWNRIGHTJoy1DPadPressed(TJoystick js)
{
  if(js.joy1_TopHat == 3) return true;
  else return false;
}
void StopDriveMotors()
{
	 	motor[RightFront] = 0;
		motor[RightBack] = 0;
 		motor[LeftFront] = 0;
 		motor[LeftBack] = 0;
}

task Inch_ArtArmUp()
{
	if(taskEnteredArtArm == false)
	{
		taskEnteredArtArm = true;
		motor[ArticArm] = 75;
 		wait1Msec(50);
 		motor[ArticArm] = 0;
 		taskEnteredArtArm = false;
 	}
}
task Inch_ArtArmDown()
{
	if(taskEnteredArtArm == false)
	{
		taskEnteredArtArm = true;
		motor[ArticArm] = -75;
 		wait1Msec(50);
 		motor[ArticArm] = 0;
 		taskEnteredArtArm = false;
 	}
}

task Inch_SlideLiftUp()
{
	if(taskEnteredSlideLift == false)
	{
		taskEnteredSlideLift = true;
		motor[SlideLift] = 75;
 		wait1Msec(60);
 		motor[SlideLift] = 0;
 		taskEnteredSlideLift = false;
 	}
}
task Inch_SlideLiftDown()
{
	if(taskEnteredSlideLift == false)
	{
		taskEnteredSlideLift = true;
		motor[SlideLift] = -75;
 		wait1Msec(60);
 		motor[SlideLift] = 0;
 		taskEnteredSlideLift = false;
 	}
}

task Inch_Forward()
{
	if(taskEntered == false)
	{
		taskEntered = true;
		motor[RightFront] = 75;
 		motor[RightBack] = 75;
 		motor[LeftFront] = 75;
 		motor[LeftBack] = 75;
 		wait1Msec(50);
 		StopDriveMotors();
 		taskEntered = false;
 	}
}

task Inch_Backward()
{
	if(taskEntered == false)
	{
		taskEntered = true;
		motor[RightFront] = -75;
 		motor[RightBack] = -75;
 		motor[LeftFront] = -75;
 		motor[LeftBack] = -75;
 		wait1Msec(50);
 		StopDriveMotors();
 		taskEntered = false;
 	}
}


task Inch_Clockwise()
{
	if(taskEntered == false)
	{
		taskEntered = true;
		motor[RightFront] = -90;
 		motor[RightBack] = -90;
 		motor[LeftFront] = 90;
 		motor[LeftBack] = 90;
 		wait1Msec(50);
 		StopDriveMotors();
// 		wait1Msec(50);
 		taskEntered = false;
 	}
}

task Inch_AntiClockwise()
{
	if(taskEntered == false)
	{
		taskEntered = true;
		motor[RightFront] = 90;
 		motor[RightBack] = 90;
 		motor[LeftFront] = -90;
 		motor[LeftBack] = -90;
 		wait1Msec(50);
 		StopDriveMotors();
// 		wait1Msec(50);
 		taskEntered = false;
 	}
}

task Spin90d_Clockwise()
{
		if(taskEntered == false)
		{
			taskEntered = true;
			Move(90, -90, SPIN(90), SPIN(90));
			taskEntered = false;
		}
}

task Spin90d_AntiClockwise()
{
		if(taskEntered == false)
		{
			taskEntered = true;
			Move(-90, 90, SPIN(90), SPIN(90));
	 		taskEntered = false;
 		}
}

#define SlideLift_Touch 2
#define ArticArm_Touch 3

task main()
{
	//initializeRobot();
  waitForStart();   // wait for start of tele-op phase

  StartTask(FrontDetectRing);
  StartTask(BackDetectRing);

	int MtrPwrLeftFront = 0;
	int MtrPwrLeftBack = 0;
	int MtrPwrRightFront = 0;
	int MtrPwrRightBack = 0;
	int MtrPwrSlideLift = 0;
	int MtrPwrArticArm = 0;

//bFloatDuringInactiveMotorPWM = false;
	nMotorPIDSpeedCtrl[SlideLift] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[ArticArm] = mtrSpeedReg;

	nMotorEncoder[RightFront] = 0;
	nMotorEncoder[RightBack] = 0;
	nMotorEncoder[LeftFront] = 0;
	nMotorEncoder[LeftBack] = 0;
	//nMotorEncoder[SlideLift] = 0; //do not reset slide and arm encoders. Because 0 represents slider or Arm in it's lowest position.
	//nMotorEncoder[ArticArm] = 0;  //They might not be in lowest position. uset test program to manually reset to lowest position if needed.

	while(1)
	{
			alive();
			getJoystickSettings(joystick);

			F_val = HTFreadSensor(F_Force); //Put the sensor values into the variables created
 	    B_val = HTFreadSensor(B_Force); //Put the sensor values into the variables created

			//Handle SlideLift Power Settings
			if(joy2Btn(4) == 1)
			{
				// Check if Slider on limit towards going up.
		    if ((HTTMUXisActive(HTTMUX, SlideLift_Touch) == false) || // sensor not touched
		  		  (nMotorEncoder[SlideLift] < 2000)) 									// OR sensor touched, however it touched at for bottom limit; in this case check the encoder value
		  		MtrPwrSlideLift = 100;
		   	else
		    	MtrPwrSlideLift = 0;
		  }
			else if(joy2Btn(2) == 1)
		  {
				// Check if Slider on limit towards going down.
		    if( (HTTMUXisActive(HTTMUX, SlideLift_Touch) == false)  || 	// sensor not touched
		    	  (nMotorEncoder[SlideLift] > 2000 )	)										// OR sensor touched, however it touched at for top limit; in this case check the encoder value
		    	MtrPwrSlideLift = -100;
		  	else
					MtrPwrSlideLift = 0;
		  }
			else
					MtrPwrSlideLift = 0;

			//Handle ArticArm Power Settings
			if(joy2Btn(3) == 1)
					MtrPwrArticArm = 100;
			else if(joy2Btn(1) == 1)
		  {
		   	if(HTTMUXisActive(HTTMUX, ArticArm_Touch)== false )
				  MtrPwrArticArm = -75;
		  	else
		  		MtrPwrArticArm = 0;
		  }
			else
					MtrPwrArticArm = 0;

			//Handle Drive Train Power Settings For the Two Joysticks
			float RtPwr = ((joystick.joy1_y1) * 0.78125);
			float LtPwr = ((joystick.joy1_y2) * 0.78125);

			//If the Value Given By the Joysticks is too low to Move the Drive Train, Set the Power to 0
			if(abs(RtPwr) <= 20)
					RtPwr = 0;
			if(abs(LtPwr) <= 20)
					LtPwr = 0;

			////////////////////////////////
			//Drive Train Power Overwrites//
			////////////////////////////////

			//If Button 4 is Pressed, Set New Power Values to Make the Robot Move Forward
			if(joy1Btn(4) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightFront = 100;
					MtrPwrRightBack = 100;
					MtrPwrLeftFront = 100;
					MtrPwrLeftBack = 100;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightFront = 75;
					MtrPwrRightBack = 75;
					MtrPwrLeftFront = 75;
					MtrPwrLeftBack = 75;
				}
				else
			  {
			  	//Changed from 40 to 35 during scrimmage
			  	MtrPwrRightFront = 40;
					MtrPwrRightBack = 40;
					MtrPwrLeftFront = 40;
					MtrPwrLeftBack = 40;
			  }
			}
			//If Button 2 is Pressed, Set New Power Values to Make the Robot Move Backward
			else if(joy1Btn(2) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightFront = -100;
					MtrPwrRightBack = -100;
					MtrPwrLeftFront = -100;
					MtrPwrLeftBack = -100;
				}
				else if(joy1Btn(10) == 1)
				{
					MtrPwrRightFront = -75;
					MtrPwrRightBack = -75;
					MtrPwrLeftFront = -75;
					MtrPwrLeftBack = -75;
				}
				else
			 	{
			 		//Changed from 40 to 35 during scrimmage
					MtrPwrRightFront = -40;
					MtrPwrRightBack = -40;
					MtrPwrLeftFront = -40;
					MtrPwrLeftBack = -40;
				}
			}
			//If Button 3 is Pressed, Set New Power Values to Make the Robot Spin Clockwise
			else if(joy1Btn(3) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightFront = -100;
					MtrPwrRightBack = -100;
					MtrPwrLeftFront = 100;
					MtrPwrLeftBack = 100;
				}
				else
				{
					MtrPwrRightFront = -50;
					MtrPwrRightBack = -50;
					MtrPwrLeftFront = 50;
					MtrPwrLeftBack = 50;
				}
			}
			//If Button 1 is Pressed, Set New Power Values to Make the Robot Spin Anticlockwise
			else if(joy1Btn(1) == 1)
			{
				if(joy1Btn(9) == 1)
				{
					MtrPwrRightFront = 100;
					MtrPwrRightBack = 100;
					MtrPwrLeftFront = -100;
					MtrPwrLeftBack = -100;
				}
				else
				{
					MtrPwrRightFront = 50;
					MtrPwrRightBack = 50;
					MtrPwrLeftFront = -50;
					MtrPwrLeftBack = -50;
				}
			}
			else if(joy1Btn(6) == 1) // spin inch clockwise
			{
				StartTask(Inch_Clockwise);
			}
			else if(joy1Btn(5) == 1) // spin inch anti-clockwise
			{
				StartTask(Inch_AntiClockwise);
			}

			//If Button 7 is Pressed, Turn 90 Degrees Left - Spin anti clock wise
			else if (IsUPJoy1DPadPressed(joystick))
			{
				//StartTask(Inch_Forward);
			}
			else if(isDOWNJoy1DPadPressed(joystick))
			{
				//StartTask(Inch_Backward);
			}
			else if(joy1Btn(7) == 1)
			{
					StartTask(Inch_Backward);
			//	StartTask(Spin90d_AntiClockwise);
			}
			//If Button 8 is Pressed, Turn 90 Degrees Right - Spin clock wise
			else if(joy1Btn(8) == 1)
			{
					StartTask(Inch_Forward);
			//	StartTask(Spin90d_Clockwise);
			}
			else if(joy2Btn(6) == 1) // arm inch up
			{
				StartTask(Inch_ArtArmUp);
			}
			else if(joy2Btn(8) == 1) // arm inch down
			{
				StartTask(Inch_ArtArmDown);
			}
			else if(joy2Btn(5) == 1) // arm inch up
			{
				StartTask(Inch_SlideLiftUp);
			}
			else if(joy2Btn(7) == 1) // arm inch down
			{
				StartTask(Inch_SlideLiftDown);
			}
			//If No Buttons Are Pressed, Move The Robot According to the Joysticks
			else
		  {
				MtrPwrRightFront = LtPwr;
				MtrPwrRightBack = LtPwr;
				MtrPwrLeftFront = RtPwr;
				MtrPwrLeftBack = RtPwr;
		  }

		  if(taskEntered == false)
			{
				taskEntered = true;
		 	 	motor[RightFront] = MtrPwrRightFront;
		 		motor[RightBack] = MtrPwrRightBack;
			 	motor[LeftFront] = MtrPwrLeftFront;
			 	motor[LeftBack] = MtrPwrLeftBack;
			 	taskEntered = false;
			}

			if(taskEnteredArtArm == false)
			{
		 	 	taskEnteredArtArm = true;
				motor[ArticArm] = MtrPwrArticArm;
				taskEnteredArtArm = false;
		 	}

		 	if(taskEnteredSlideLift == false)
			{
				taskEnteredSlideLift = true;
		 		motor[SlideLift] = MtrPwrSlideLift;
		 		taskEnteredSlideLift = false;
		 	}

			wait1Msec(50);
	}
}
