#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTTMUX,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.0\drivers\hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.0\drivers\hitechnic-touchmux.h"

const tMUXSensor HTEOPD = msensor_S2_1;
const tMUXSensor IR_right = msensor_S2_2;
const tMUXSensor IR_left = msensor_S2_3;

#define SlideLift_Touch 2
#define ArticArm_Touch 3

task main()
{
//bFloatDuringInactiveMotorPWM = false;  // the motors will NOT coast when power is not applied
	nMotorPIDSpeedCtrl[ArticArm] = mtrSpeedReg;
  while (true)
  {
	    //If the left button is pressed on the nxt, move the arm down
	    if(nNxtButtonPressed == 2)
	      motor[ArticArm] = -60;
	    	    //If the right button is pressed on the nxt, move the arm up
	    else if(nNxtButtonPressed == 1)
	      motor[ArticArm] = 100;
	    //If no buttons on the NXT are pressed, dont move the arm
	    else if(nNxtButtonPressed == -1)
	      motor[ArticArm] = 0;
	    wait10Msec(1);

	    if(HTTMUXisActive(HTTMUX, SlideLift_Touch))
	    	nxtDisplayTextLine(3, "SlideLift Pressed");
	   	else
			 	nxtDisplayTextLine(3, "SlideLift Not");

			if(HTTMUXisActive(HTTMUX, ArticArm_Touch))
	    	nxtDisplayTextLine(5, "ArticArm Pressed");
	   	else
			 	nxtDisplayTextLine(5, "ArticArm Not");
  }
}
