#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTTMUX,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.0/drivers/hitechnic-sensormux.h"

#include "rdpartyrobotcdr-3.0/drivers/hitechnic-irseeker-v2.h"

// Give the sensor a nice easy to use name
const tMUXSensor RightIR = msensor_S2_3;
const tMUXSensor LeftIR = msensor_S2_2;

int LdirAC = 0;
int LS1, LS2, LS3, LS4, LS5 = 0;

task ReadIR ()
{
	eraseDisplay();

  while(true)
  {
    // Read the current non modulated signal direction
    LdirAC = HTIRS2readACDir(LeftIR);
    if (LdirAC < 0)
      break; // I2C read error occurred

    // Read the individual signal strengths of the internal sensors
    // Do this for both Sensors
    if (!HTIRS2readAllACStrength(LeftIR, LS1, LS2, LS3, LS4, LS5))
      break; // I2C read error occurred

   	nxtDisplayTextLine(1, "D  %d", LdirAC);
    nxtDisplayTextLine(2, "1  %d", LS1);
    nxtDisplayTextLine(3, "2  %d", LS2);
    nxtDisplayTextLine(4, "3  %d", LS3);
    nxtDisplayTextLine(5, "4  %d", LS4);
    nxtDisplayTextLine(6, "5  %d", LS5);

    wait10Msec(5);
  }
}

task main ()
{
  StartTask(ReadIR);

  while(1)
  {
  	int CurrentDir = LdirAC;

  	while(CurrentDir == LdirAC)
  	{
  		motor[RightFront] = 40;
		 	motor[RightBack] = 40;
			motor[LeftFront] = 40;
			motor[LeftBack] = 40;

			wait1Msec(1);
  	}

		while(nNxtButtonPressed != 3)
		{
			motor[RightFront] = 0;
			motor[RightBack] = 0;
			motor[LeftFront] = 0;
			motor[LeftBack] = 0;
		}
	}
}
