#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S3,     HTTMUX,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     LeftFront,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftBack,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     RightFront,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightBack,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     SlideLift,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     ArticArm,      tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "rdpartyrobotcdr-3.0/drivers/hitechnic-sensormux.h"
#include "rdpartyrobotcdr-3.0/drivers/hitechnic-irseeker-v2.h"

// Give the sensor a nice easy to use name
const tMUXSensor RightIR = msensor_S2_2;
const tMUXSensor LeftIR = msensor_S2_3;

task main ()
{
  int LdirAC = 0;
  int RdirAC = 0;
	int LS1, LS2, LS3, LS4, LS5 = 0;
	int RS1, RS2, RS3, RS4, RS5 = 0;

  eraseDisplay();

  while(true)
  {
    // Read the current non modulated signal direction
    LdirAC = HTIRS2readDCDir(LeftIR);
    if (LdirAC < 0)
      break; // I2C read error occurred

    // read the current modulated signal direction
    RdirAC = HTIRS2readDCDir(RightIR);
    if (RdirAC < 0)
      break; // I2C read error occurred

    // Read the individual signal strengths of the internal sensors
    // Do this for both Sensors
    if (!HTIRS2readAllDCStrength(LeftIR, LS1, LS2, LS3, LS4, LS5))
      break; // I2C read error occurred
    if (!HTIRS2readAllDCStrength(RightIR, RS1, RS2, RS3, RS4, RS5))
      break; // I2C read error occurred

   	nxtDisplayTextLine(1, "D  %d    %d", LdirAC, RdirAC);
    nxtDisplayTextLine(2, "1  %d    %d", LS1, RS1);
    nxtDisplayTextLine(3, "2  %d    %d", LS2, RS2);
    nxtDisplayTextLine(4, "3  %d    %d", LS3, RS3);
    nxtDisplayTextLine(5, "4  %d    %d", LS4, RS4);
    nxtDisplayTextLine(6, "5  %d    %d", LS5, RS5);

    wait10Msec(5);
  }
}
